apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dynatrace-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: oci://public.ecr.aws/dynatrace/dynatrace-operator
